### ISSUE TITLE
Minor "Active Issues" Updates

### ISSUE THREAD

**Issue by kt-wawro** [jbarnes850/pldg-dashboard#8]
- Fil-B Link Broken and returns a 404 Error

- Drand needs a button that links to it's [repo](https://github.com/drand/drand/issues?q=is%3Aopen+is%3Aissue+label%3Adevguild)

**Comment by jbarnes850** [comment]
Thanks for flagging this @kt-wawro! Will make sure to revise this asap.

**Comment by jbarnes850** [comment]
@kt-wawro this has been resolved! Thanks again for flagging, see the commit here: https://github.com/jbarnes850/pldg-dashboard/commit/228d133bfd1fa0ff14416353539d87bb80a45316
